---
title: '整理短信的规则'
output: github_document
---

```{sql eval=F}
select 
    content
from t181115_subsetmainsms_ljx
order by rand(123)
limit 100
```

```{r eval=FALSE, include=FALSE}
library(RODBC)
impala <- odbcConnect("Impala")
```

```{r eval=FALSE, include=FALSE}
prt_data_100 <- sqlQuery(impala,"
    select 
        content
    from xyjl.t181115_subsetmainsms_ljx
    order by rand(123)
    limit 100
                         ")
```

```{r eval=FALSE, include=FALSE}
prt_data_100
```

```{r}
library(rebus)
```

```{r}
or('http','cn')
START %R%
    '【' %R%
    one_or_more(ANY_CHAR) %R%
    '】'
'额度'
'\\d{4,}'
```

`(?:http|cn)`

```{sql eval=F}
select content
from xyjl.t181115_subsetmainsms_ljx
where
    regexp_like(content,'(?:http|cn)')
    and regexp_like(content,'额度')
    and regexp_like(content,'\\d{4,}')
    and !regexp_like(content,'审核')
order by rand(123)
```

```{sql eval=F}
select 
    avg(
        regexp_like(content,'(?:http|cn)')
        and regexp_like(content,'额度')
        and regexp_like(content,'\\d{4,}')
        -- and !regexp_like(content,'审核')
        -- 干扰很少
    )
from xyjl.t181115_subsetmainsms_ljx
```


1. `avg(A and B and C and !D)` > 5%
1. `rand(123)` 100个，查看准确率
1. `avg(A and B and C and !D and E)` > 5%