install.packages("rpart")
library(rpart)
install.packages("rpart.plot")
library(rpart.plot)
install.packages("caret")
library(lattice)
library(ggplot2)
library(caret)
setwd("C:/Users/lianxiang/Desktop")
X1<- read.csv("X1.csv")
set.seed(1000)
t.idx <- createDataPartition(X1$roe, p=0.7, list = FALSE)
bfit <- rpart(roe ~ ., data = X1[t.idx,2:31])
bfit
plot(bfit)