---
title: "code log"
output: github_document
---

### 2018-12-12 20:22:21

需求定义

每行: 每个客户-关联联系人的手机号
每列: 关联联系人编号 1,2,3

这个联系人编号有讲究吗？
比如第一联系人、第二联系人

```{r}
library(tidyverse)
df <- data.frame(id = sort(c(rep(letters[1:3], each = 2), 'a', 'a', 'b', 'd')),
                 name = LETTERS[1:10],
                 phone = 0:9)
df %>% 
    group_by(id) %>% 
    nest
```


### 2018-12-12 16:12:23

1. 更新数据集

### 2018-12-12 14:50:56

```{r}
df <- data.frame(id = c('a', 'a', 'b'), phone = c(111, 222, 333), name = c('Bob', 'John', 'Tom')); df

df <- df %>% group_by(id) %>% mutate(number = 1:length(id))

df_1 <- df %>% filter(number == 1) %>% select(-number)
df_2 <- df %>% filter(number == 2) %>% select(-number)

df_1 %>% left_join(df_2, by = 'id')
```

### 2018-12-12 14:31:27

```{r}
df <- data.frame(id = c('a', 'a', 'b'), p = c(1, 2, 1), d = c('A', 'B', 'A')); df
df2 <- data.frame(id = c('a', 'b'), p_1 = c(1, 1), p_2 = c(2, NA), d_1 = c('A', 'A'), d_2 = c('B', NA)); df2
```

```{r}
library(tidyverse)
df %>%
    gather(key,value,-id) %>% 
    # 数据非唯一，因此需要加额外标签
    mutate(key = str_c(key,value,sep = '_')) %>% 
    spread(key,value)
```



```{r}
# LETTERS 需要数字化，用如下表格替换即可
tibble(
    upper = LETTERS
) %>% 
    mutate(num = row_number())
```

